// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi6E5PSp4x9BI0CSQdQIquM-zyYm-0TWE',
    appId: '1:903744720307:web:aad80d0f7b0cd1d13e8fc6',
    messagingSenderId: '903744720307',
    projectId: 'blessed-6a409',
    authDomain: 'blessed-6a409.firebaseapp.com',
    storageBucket: 'blessed-6a409.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWdOpenbu71EMmg5nQJ8ejcneVCCKGcCA',
    appId: '1:903744720307:android:c6f059656686f25c3e8fc6',
    messagingSenderId: '903744720307',
    projectId: 'blessed-6a409',
    storageBucket: 'blessed-6a409.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyeDGqal8e6hbHIQMeeACemeUH5rPy0KA',
    appId: '1:903744720307:ios:5aab6aac6e82dd1b3e8fc6',
    messagingSenderId: '903744720307',
    projectId: 'blessed-6a409',
    storageBucket: 'blessed-6a409.appspot.com',
    iosClientId: '903744720307-66qsiele20sjak31488upgq1ngq93pv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.misis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyeDGqal8e6hbHIQMeeACemeUH5rPy0KA',
    appId: '1:903744720307:ios:5aab6aac6e82dd1b3e8fc6',
    messagingSenderId: '903744720307',
    projectId: 'blessed-6a409',
    storageBucket: 'blessed-6a409.appspot.com',
    iosClientId: '903744720307-66qsiele20sjak31488upgq1ngq93pv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.misis',
  );
}
